[workspace]
members = ["bin/*", "plugins/*"]
resolver = "2"

[workspace.dependencies]
# plugins
car = { path = "plugins/car" }
laptag = { path = "plugins/laptag" }
track = { path = "plugins/track" }
resurfacer = { path = "plugins/resurfacer" }
scoreboard = { path = "plugins/scoreboard" }

# bevy
avian2d = { version = "0.1" }
bevy = { version = "0.14", default-features = false }
bevy_anyhow_alert = "0.3"
bevy_prng = { version = "0.7", features = ["wyrand"] }
bevy_rand = { version = "0.7", features = ["wyrand"] }
bevy_reactive_blueprints = { git = "https://github.com/snendev/bevy-reactive-blueprints" }
bevy_rts_camera = { git = "https://github.com/snendev/bevy_rts_camera_2d" }
sickle_ui = { git = "https://github.com/UmbraLuminosa/sickle_ui", rev = "2f2fae9" }

# stdx
anyhow = "1.0"
rand_core = { version = "0.6" }
simple-easing = { version = "1.0" }
thiserror = "1.0"

[package]
name = "tagcar"
version = "0.1.0"
edition = "2021"

[features]
default = []
debug = []

[dependencies]
# plugins
resurfacer = { workspace = true, features = ["graphics"] }
track = { workspace = true, features = ["graphics"] }
laptag = { workspace = true }
scoreboard = { workspace = true }
car = { workspace = true }
sickle_ui = { workspace = true }

# bevy
avian2d = { workspace = true, features = ["debug-plugin"] }
bevy = { workspace = true, default-features = true }
bevy_reactive_blueprints = { workspace = true }

# stdx
simple-easing = { workspace = true }
